### ISSUE TITLE
Question on Unwrapped and wrapped

### ISSUE THREAD

**Issue by srph** [jdlehman/alt-example-tests#1]
Is there another way besides exporting both and unwrapped? :smile:. Thanks for this repo, by the way.

**Comment by srph** [comment]
Please don't mind ;). I just reread the tests.

**Comment by jdlehman** [comment]
You do not need to export both to test. This is just showing how you can also export the unwrapped class, which gives you greater flexibility in your testing.

It is perfectly valid to export the wrapped alt store only.  You can test it indirectly by calling actions and checking the resulting store values as depicted by the [first part](https://github.com/jdlehman/alt-example-tests/blob/master/test/stores/PetStore_test.js#L9-L43) of the test.

Another tool you could use is the [AltTestingUtils](https://github.com/goatslacker/alt/blob/master/utils/AltTestingUtils.js).

**Comment by srph** [comment]
Thanks!
