### ISSUE TITLE
Add Phantomjs to package.json dependencies

### ISSUE THREAD

**Issue by noahmonster** [jdlehman/alt-example-tests#4]
The tests don't run without PhantomJS.  Adding it to the package.json dependencies should fix this.

**Comment by jdlehman** [comment]
Thanks for making this note. [This commit](https://github.com/jdlehman/alt-example-tests/commit/93db525d8bbb39ad68643c1b7eb9c270a0640db6) should take care of it.

**Comment by noahmonster** [comment]
It looks like the karma-phantomjs-launcher needs to be updated to the latest (1.0.1) in order to work with the latest phantomJS.

**Comment by jdlehman** [comment]
i updated the deps (except for alt), so this should all work now. I had phantomjs on my machine already so I didnt notice. I'll go through and update alt later 😃
