### ISSUE TITLE
Alt Dispatch Never Fires

### ISSUE THREAD

**Issue by BigPrimeNumbers** [jdlehman/alt-example-tests#5]
So I'm learning how to test Alt Actions (and React components), and followed your simple, straightforward example, but can't get it to work as expected. My version is somewhat simplified: 

```javascript
import alt from '../../utils/alt'
import Actions from '../../actions/Foo'
import sinon from 'sinon'

// using [sinon](http://sinonjs.org/docs/) for spying

describe('Actions', function() {
    beforeEach(function() {
        this.dispatcherSpy = sinon.spy(alt.dispatcher, 'dispatch')
    })

    afterEach(function() {
        // clean up our sinon spy so we do not affect other tests
        alt.dispatcher.dispatch.restore()
    })

    describe('#testList', function() {
        it('dispatches correct data', function() {
            // fire the action
            Actions.get({id:"1234"})
            // use our spy to see what payload the dispatcher was called with
            // this lets us ensure that the expected payload was fired
            var dispatcherArgs = this.dispatcherSpy.args[0]
            var firstArg = dispatcherArgs[0]
            console.log("TESTING", this.dispatcherSpy.calledOnce)

            expect(firstArg && firstArg.action).toBe(Actions.GET)
            expect(firstArg.data).toEqual({id:"1234"})
      })
  })
})
```

It appears that the `dispatcherSpy` never gets called, even though it appears that it should when the `Alt` action `Get` fires. Instead I get the error:

`SourceMap position not found for trace: TypeError: undefined is not an object (evaluating 'dispatcherArgs[0]')`

or if I comment out the two lines above the `console.log`, the log prints `false` confirming that the dispatcher never gets called. Any ideas?

**Comment by jdlehman** [comment]
Hmmm. out of curiosity what build tool are you using? I remember we have seen issues in the past when people have tried to do: 

```
// utils/alt.js
import Alt from 'alt';
export default new Alt();
```

some build tools transpile will transpile this export such that any import will call `new Alt()`, while others will store `new Alt()` to a variable and share that reference to each of the import calls.

I know that webpack does the latter, which is why this setup works in this repo. You can try putting all your actions and stores in a single file to see if the problem is what I suspect (it should work if everything is inline, and then we will know that the problem is how the import/exports are being transpiled). If it is, you will need to make sure your actions and stores are all getting the same instance of alt. It might be as simple as something like:

```
import Alt from 'alt';
const altInstance = new Alt();
export default altInstance;
```

**Comment by BigPrimeNumbers** [comment]
You are correct in that it appears that using 

```
// utils/alt.js
import Alt from 'alt'

const alt = new Alt()

import chromeDebug from 'alt-utils/lib/chromeDebug'
chromeDebug(alt)

export default alt
```

Is the culprit (if i move the `Action` class to the test file, it runs properly), but we are in fact using `webpack`, and I'm seeing this aberrant behavior. I'm not very familiar with `webpack`, but here is our file:

``` javascript
import webpack from 'webpack'
import path from 'path'
import settings from './settings'

const source = path.resolve(__dirname, '../javascript')

module.exports = {
    //devtool: 'eval-cheap-module-source-map', // nice, but slow
    devServer: {
        hot: true,
        inline: true,
        host: '0.0.0.0',
        headers: {'Access-Control-Allow-Origin': '*'},
        port: settings.development.port
    },

    context: source,

    entry: {
        server: 'webpack/hot/only-dev-server',
        app: './app.js'
    },

    output: {
        filename: '[name].js',
        publicPath: `${settings.development.server}/`
    },

    module: {
        loaders: [
            {
                test: /\.js$/,
                include: source,
                exclude: /server\.js/,
                loaders: ['react-hot', 'babel']
            },
            {
                test: /\.styl/,
                loaders: ['style', 'css?modules&localIdentName=[local]___[hash:base64:10]', 'stylus']
            }
        ]
    },

    plugins: [
        new webpack.optimize.CommonsChunkPlugin('common', 'common.js'),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin()
    ]

}
```

Thanks for you help with this!

**Comment by jdlehman** [comment]
Hmm. Interesting that it doesn't necessarily work with webpack like I thought. I wonder if its a version thing. Either way, I am going to update the docs/code so that no one else has to chase down the same problem. Thanks for reporting!

**Comment by BigPrimeNumbers** [comment]
Any advice for getting around this weird behavior? Using what we discussed above gets rid of errors, but still doesn't run the tests appropriately. I tried creating a singleton instance in our `../utila/alt.js` file with:

``` javascript
import Alt from 'alt'
import chromeDebug from 'alt-utils/lib/chromeDebug'

var instance = null

class singletonAlt extends Alt{
    constructor() {
        super()
        if(!instance){
            instance = this
            chromeDebug(instance)
        }
        return instance
    }
} export default new singletonAlt()
```

but to no avail; same weird issue with different instances of `ALT` being used. Any ideas?

**Comment by jdlehman** [comment]
You can try:

```
// utils/alt.js
import Alt from 'alt';
import chromeDebug from 'alt-utils/lib/chromeDebug';

const altInstance = chromeDebug(new Alt());
export default altInstance
```

If that doesn't work, I am out of ideas 😞

**Comment by BigPrimeNumbers** [comment]
Using my singleton above, the instance of `Alt` is definitely identical in different imports (I gave it an `id` of a random number in the `if` clause, and it is the same wherever I import it). It still doesn't seem to catch any dispatches made from outside the test file though. Is it possible this is an issue with `sinon`? I had to use `sinon 2.0.0-pre.3` to get this project up and running at all - something to do with `sinon 1.*` not playing nice with `import`.

**Comment by jdlehman** [comment]
Definitely could be sinon, I have had issues with it in the past. A project I was working on was locked on an older version of sinon because of issues with newer versions working with `import`.

You could try [expect](https://github.com/mjackson/expect#spies)

**Comment by BigPrimeNumbers** [comment]
That didn't work either. I'm beginning to suspect it has something to do with the asynchronous nature of the `Alt` dispatch. I'm wondering if there's some place to insert a `then` in order to wait for the dispatch to return.

**Comment by jdlehman** [comment]
While the effects of the dispatch are async, we are spying on the part of alt that makes the dispatch call, which is synchronous.

**Comment by jdlehman** [comment]
Do the tests in this repo work for you locally?

**Comment by BigPrimeNumbers** [comment]
@Yep they work fine if I put the `actions` class in the test file, and create them with `Alt` right there. If I try to use the external `actions.js` file, it stops working as expected (`alt dispatch` never reports as "fired").
